apiVersion: apps/v1
kind: Deployment
metadata:
  name: rss-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rss-service
  template:
    metadata:
      labels:
        app: rss-service
    spec:
       containers:
        - name: rss-service
          image: stevenxs/rss-service
          imagePullPolicy: Always
          ports:
          - containerPort: 8180
            name: "http"
---
apiVersion: v1
kind: Service
metadata:
  name: rss-service
spec:
   selector:
     app: rss-service
   ports:
   - name: http
     protocol: TCP
     port: 8180
     targetPort: 8180
   type: LoadBalancer