spring:
  application:
    name: rss-service
  datasource:
    url: jdbc:h2:mem:rss
    driverClassName: org.h2.Driver
    username: kpayares
    password: kpayares
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true


server:
  port: 8180
  
endpoint:
  url: http://feeds.nos.nl/nosjournaal?format=